### ISSUE TITLE
YAML 语法

### ISSUE THREAD

**Issue by dkluffy** [dkluffy/dklog#30]
### 一个字典是由一个简单的 键: 值 的形式组成(这个冒号后面必须是一个空格)

```yaml
---
# 一个美味水果的列表
- Apple
- Orange
- Strawberry
- Mango

# 一位职工的记录
name: Example Developer
job: Developer
skill: Elite
```
### bool

```yaml
---
# 一位职工记录
name: Example Developer
job: Developer
skill: Elite
employed: True
foods:
    - Apple
    - Orange
    - Strawberry
    - Mango
languages:
    ruby: Elite
    python: Elite
    dotnet: Lame
```
### Ansible 使用 “{{ var }}” 来引用变量. 如果一个值以 “{” 开头, YAML 将认为它是一个字典, 所以我们必须引用它, 像这样:

`foo: "{{ variable }}"`
