### ISSUE TITLE
ansible 连接 telnet （cisco iou console）的例子

### ISSUE THREAD

**Issue by dkluffy** [dkluffy/dklog#35]
关于`委托`:
以下这个例子就是`委托`本地（即运行ansible的机器去运行命令），而不是在远程（目标）上运行。

结合以下这个脚本，可以用于IOU实验，对多台机器，一键执行复杂命令：
[telcisco.py](https://github.com/dkluffy/dklog/blob/master/my_code/todos/telcisco.py)
P.S.: 无缘无故浪费一个下午，，， 等需要用了在完善这个脚本

```
---

- hosts: webservers
  serial: 5

  tasks:

  - name: take out of load balancer pool
    command: /usr/bin/take_out_of_pool {{ inventory_hostname }}
    delegate_to: 127.0.0.1

  - name: actual steps would go here
    yum: name=acme-web-stack state=latest

  - name: add back to load balancer pool
    command: /usr/bin/add_back_to_pool {{ inventory_hostname }}
    delegate_to: 127.0.0.1
```

_Originally posted by @dkluffy in https://github.com/dkluffy/dklog/issues/31#issuecomment-590318680_

**Comment by dkluffy** [comment]
```
---
- name: interact telnet
  shell: |
          set timeout 10
          log_file "/tmp/iou_log.log"

          spawn telnet {{ inventory_hostname }} {{ port }} 
          sleep 5
          send "\r\n"   #这行在IOU里是必须的，因为连接的是console
          send "!\n"
          send "!\n"
          send "!\n"

          send "!\n"
          send "enable\n"
          expect "#"
          send "sh ip route\n"
          send "\n"
          expect "#"
          set output [open "/tmp/outputfile.txt" "a+"]

  args:
          executable: /usr/bin/expect
  changed_when: yes
  delegate_to: localhost
```

**Comment by dkluffy** [comment]
[stackoverflow](https://stackoverflow.com/questions/52837619/ansible-wont-connect-to-emulated-network-devices-over-telnet)
I would solve this using the shell module combined with /usr/bin/expect as the executable. This gives you more flexibility to interacting with the system, and makes it possible to follow progress in a separate log file.

```yaml
- name: Interact with system
  shell: |
    set timeout 120
    log_file {{ '~/logs/your_log_file.explog' }}

    spawn telnet {{ inventory_hostname }}

    expect "username: "
    send "{{ your_username }}\n"

    expect "password:"
    send "{{ your_password }}\n"

    expect "# "
    send "term length 0"

    expect "# "
    send "en"

    expect "# "
    send "conf -t"
  args:
    executable: /usr/bin/expect
  changed_when: yes
  delegate_to: localhost
```
Or you can use the script module to keep your playbooks tidy and clean.

```yaml
- name: Interact with system
  script: interact-with-system.expect
  args:
    executable: /usr/bin/expect
  changed_when: yes
  delegate_to: localhost
```
PS: If you use a shebang, you don't even need to add the executable.

**Comment by dkluffy** [comment]
如果输出很长，遇到 " -- more ---",可以 先发送这个命令,注意是`conf t`之前。
`#terminal length 0`

**Comment by dkluffy** [comment]
### 官方 shell_model 的例子
[shell_model ](https://docs.ansible.com/ansible/latest/modules/shell_module.html)
```yaml
- name: Execute the command in remote shell; stdout goes to the specified file on the remote.
  shell: somescript.sh >> somelog.txt

- name: Change the working directory to somedir/ before executing the command.
  shell: somescript.sh >> somelog.txt
  args:
    chdir: somedir/

# You can also use the 'args' form to provide the options.
- name: This command will change the working directory to somedir/ and will only run when somedir/somelog.txt doesn't exist.
  shell: somescript.sh >> somelog.txt
  args:
    chdir: somedir/
    creates: somelog.txt

# You can also use the 'cmd' parameter instead of free form format.
- name: This command will change the working directory to somedir/.
  shell:
    cmd: ls -l | grep log
    chdir: somedir/

- name: Run a command that uses non-posix shell-isms (in this example /bin/sh doesn't handle redirection and wildcards together but bash does)
  shell: cat < /tmp/*txt
  args:
    executable: /bin/bash

- name: Run a command using a templated variable (always use quote filter to avoid injection)
  shell: cat {{ myfile|quote }}

# You can use shell to run other executables to perform actions inline
- name: Run expect to wait for a successful PXE boot via out-of-band CIMC
  shell: |
    set timeout 300
    spawn ssh admin@{{ cimc_host }}

    expect "password:"
    send "{{ cimc_password }}\n"

    expect "\n{{ cimc_name }}"
    send "connect host\n"

    expect "pxeboot.n12"
    send "\n"

    exit 0
  args:
    executable: /usr/bin/expect
  delegate_to: localhost

# Disabling warnings
- name: Using curl to connect to a host via SOCKS proxy (unsupported in uri). Ordinarily this would throw a warning.
  shell: curl --socks5 localhost:9000 http://www.ansible.com
  args:
    warn: no
```
